### ISSUE TITLE
Problem with building python module if --program-suffix is used

### ISSUE THREAD

**Issue by dvdesolve** [plumed/plumed2#469]
I keep two versions of plumed on my PC: serial and MPI. I build MPI version with this line:
```
./configure --prefix=/usr --enable-mpi --program-suffix=-mpi
```

Then during build I get the following error:
```
cp -pr ../../python install 
cd install/python && rm -fr *.so plumed.cpp build && \
          unset CXX && unset CC && unset CFLAGS && unset CXXFLAGS && unset LDSHARED && \
          plumed_program_name="plumed-mpi" \
          plumed_version=2.5.1 \
          plumed_include_dir=../../../wrapper \
          plumed_default_kernel="/usr/lib/libplumed-mpiKernel.so" \
          python setup.py build_ext -i
Module name plumed-mpi
Version number 2.5.1
Hardcoded PLUMED_KERNEL /usr/lib/libplumed-mpiKernel.so
plumed.cpp not found, cython is needed
importing cython
Compiling plumed.pyx because it changed.
[1/1] Cythonizing plumed.pyx

Error compiling Cython file:
------------------------------------------------------------
...
#/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
^
------------------------------------------------------------

plumed.pyx:1:0: 'plumed-mpi' is not a valid module name
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    ext_modules=cythonize(ext_modules)
  File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: plumed.pyx
make[2]: *** [Makefile:283: install] Error 1
make[2]: leaving directory «/opt/buildcache/makepkg/plumed-mpi/src/plumed-2.5.1/src/lib»
make[1]: *** [Makefile:11: install] Error 2
make[1]: leaving directory «/opt/buildcache/makepkg/plumed-mpi/src/plumed-2.5.1/src»
make: *** [Makefile:35: install] Error 2
```

Seems like python module doesn't respect configure options

**Comment by GiovanniBussi** [comment]
@dvdesolve can you check if branch fix-469 fixes the problem? Thanks! Giovanni

**Comment by dvdesolve** [comment]
build just fine! thank you.
