### ISSUE TITLE
DRR module not recognized in Amber20

### ISSUE THREAD

**Issue by jfloresc** [plumed/plumed2#612]
I am trying to test the DRR module in Amber20, so far the lines DRR ... are not recognized:

`+++ Loading the PLUMED kernel runtime +++
+++ PLUMED_KERNEL="/mnt/software/plumed/2.6.1.DRR/lib/libplumedKernel.so" +++
PLUMED: PLUMED is starting
PLUMED: Version: 2.6.1 (git: Unknown) compiled on Sep  5 2020 at 23:58:50
PLUMED: Please cite these papers when using PLUMED [1][2]
PLUMED: For further information see the PLUMED web page at http://www.plumed.org
PLUMED: Root: /mnt/software/plumed/2.6.1.DRR/lib/plumed
PLUMED: For installed feature, see /mnt/software/plumed/2.6.1.DRR/lib/plumed/src/config/config.txt
PLUMED: Molecular dynamics engine: amber
PLUMED: Precision of reals: 8
PLUMED: Running over 1 node
PLUMED: Number of threads: 1
PLUMED: Cache line size: 512
PLUMED: Number of atoms: 1912
PLUMED: File suffix: 
PLUMED: FILE: plumed.dat
PLUMED: Action TORSION
PLUMED:   with label phi
PLUMED:   between atoms 5 7 9 15
PLUMED:   using periodic boundary conditions
PLUMED: Action TORSION
PLUMED:   with label psi
PLUMED:   between atoms 7 9 15 17
PLUMED:   using periodic boundary conditions
PLUMED: ERROR
PLUMED: I cannot understand line: DRR LABEL=eabf ARG=phi,psi FULLSAMPLES=500 GRID_MIN=-pi,-pi GRID_MAX=pi,pi GRID_BIN=180,180 FRICTION=8.0,8.0 TAU=0.5,0.5 OUTPUTFREQ=50000 HISTORYFREQ=500000
PLUMED: Maybe a missing space or a typo?
PLUMED: 
PLUMED: ################################################################################
PLUMED: 
PLUMED: 
PLUMED: +++ PLUMED error
PLUMED: +++ at PlumedMain.cpp:670, function void PLMD::PlumedMain::readInputWords(const std::vector<std::__cxx11::basic_string<char> >&)
PLUMED: +++ message follows +++
PLUMED: ERROR
PLUMED: I cannot understand line: DRR LABEL=eabf ARG=phi,psi FULLSAMPLES=500 GRID_MIN=-pi,-pi GRID_MAX=pi,pi GRID_BIN=180,180 FRICTION=8.0,8.0 TAU=0.5,0.5 OUTPUTFREQ=50000 HISTORYFREQ=500000
PLUMED: Maybe a missing space or a typo?
PLUMED: 
PLUMED: ################################################################################
PLUMED: 
terminate called after throwing an instance of 'PLMD::ExceptionError'
  what():  
+++ PLUMED error
+++ at PlumedMain.cpp:670, function void PLMD::PlumedMain::readInputWords(const std::vector<std::__cxx11::basic_string<char> >&)
+++ message follows +++
ERROR
I cannot understand line: DRR LABEL=eabf ARG=phi,psi FULLSAMPLES=500 GRID_MIN=-pi,-pi GRID_MAX=pi,pi GRID_BIN=180,180 FRICTION=8.0,8.0 TAU=0.5,0.5 OUTPUTFREQ=50000 HISTORYFREQ=500000
Maybe a missing space or a typo?

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7fbea3a28ef7 in ???
#1  0x7fbea3a2812d in ???
#2  0x7fbea34604bf in ???
#3  0x7fbea3460438 in ???
#4  0x7fbea3462039 in ???
#5  0x7fbea3dd7ddd in ???
#6  0x7fbea3de3895 in ???
#7  0x7fbea3de3900 in ???
#8  0x7fbea3de3ba8 in ???
#9  0x7fbea1b9fa9d in ???
#10  0x7fbea1bafb74 in ???
#11  0x4d2e3f in ???
#12  0x50b10a in ???
#13  0x41f7ec in ???
#14  0x7fbea344b83f in ???
#15  0x41f828 in ???
#16  0xffffffffffffffff in ???
run_cuda.sh: line 11: 114254 Aborted                 (core dumped) pmemd -O -i ${name}.mdin -p ${top} -c ${nameprev}.rst7 -ref ${init} -o ${files}.mdout -x ${files}.nc -r ${files}.rst7 -inf ${files}.mdinfo
`

The two lines were added to the mdin:
    plumed = 1,
    plumedfile = 'plumed.dat',

This error corresponds to pmemd, and the same happens with pmemd.cuda or pmemd.MPI.

I have enabled the DRR module as follows:
./configure --enable-modules=drr --enable-boost_serialization --prefix=PATH
"-L /local/libraries/lib/boost/1.71/lib -lboost_serialization" to DYNAMIC_LIBS

**Comment by jfloresc** [comment]
Someone had found the solution here: https://groups.google.com/g/plumed-users/c/rTqmLBSJruI/m/_iwjodsjDQAJ
