### ISSUE TITLE
Multi replicas simulation with OpenMM-Plumed plugin

### ISSUE THREAD

**Issue by husseinmur** [plumed/plumed2#947]
Hello,

I am trying to run a Metadynamics Metainference simulation with multi replicas using OpenMM and Plumed. I am using the [OpenMM-Plumed](https://github.com/openmm/openmm-plumed) plugin to add the Plumed script to the forcefield. 

Although I managed to run it for one replica, it seems like the plugin doesn't support multi replicas right now. I modified its source code and passed an MPI communicator from Python to C++ through Swig, then used `plumed_cmd(plumedmain, "setMPIComm", &comm);` to set the communicator. Now, Plumed output shows that it is running on multiple nodes (whatever number I choose after the np flag when I run `mpirun -np 4 python simulate.py`), but still the number of replicas shown in the output is 1. I looked at the Gromacs patch and figured that I need to add another communicator, there should be inter and intra comms, is that right?

I passed another one and wrote the following piece of code to make use of the comms:
```
int done_already;
int intra_comm_rank;
MPI_Initialized(&done_already);
MPI_Comm intra_comm = force.getIntracom();
MPI_Comm inter_comm = force.getIntercom();
MPI_Comm_rank(intra_comm, &intra_comm_rank);
if (!done_already)
{
    MPI_Init(NULL, NULL);
}
if (intra_comm_rank == 0)
    plumed_cmd(plumedmain, "GREX setMPIIntercomm", &inter_comm);
plumed_cmd(plumedmain, "GREX setMPIIntracomm", &intra_comm);
plumed_cmd(plumedmain, "GREX init");
```
After the changes, the Python script hangs when I run it with MPI and doesn't show any output. However, if include the GREX commands inside the `if (!done_already)`, it shows the following error message:
```
Traceback (most recent call last):
  File "/mnt/f/CALVADOS/single_chain/ACTR/mpi/simulate.py", line 149, in <module>
    simulation.minimizeEnergy()
  File "/home/hussein/miniconda3/envs/try4/lib/python3.9/site-packages/openmm/app/simulation.py", line 137, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/hussein/miniconda3/envs/try4/lib/python3.9/site-packages/openmm/openmm.py", line 17208, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException:
+++ PLUMED error
+++ message follows +++
This command expects a floating point type. Received a void instead
```
Should the Intercommunicator be passed from the Python script just like the Intracommunicator? Is there something I am missing?

Here are the relevant code snippet for reference:

The Swig file:
```
%module openmmplumed


%import(module="simtk.openmm") "swig/OpenMMSwigHeaders.i"
%include "swig/typemaps.i"
%include "std_string.i"
%include "/home/hussein/miniconda3/lib/python3.9/site-packages/mpi4py/include/mpi4py/mpi4py.i"
%mpi4py_typemap(Comm, MPI_Comm);

%{
#include "PlumedForce.h"
#include "OpenMM.h"
#include "OpenMMAmoeba.h"
#include "OpenMMDrude.h"
#include "openmm/RPMDIntegrator.h"
#include "openmm/RPMDMonteCarloBarostat.h"
#include <mpi.h>
%}

%pythoncode %{
import simtk.openmm as mm
%}

namespace PlumedPlugin {

class PlumedForce : public OpenMM::Force {
public:
    PlumedForce(const std::string& script, const MPI_Comm intra_comm, const MPI_Comm inter_comm);
    const std::string& getScript() const;
};

}
```

The Python script (snippet that involves MPI):
```
comm1 = MPI.COMM_WORLD
comm2 = MPI.COMM_WORLD
system.addForce(PlumedForce(script, comm1, comm2))
simulation = Simulation(top, system, integrator)
    
simulation.context.setPositions(pdb.positions)

simulation.minimizeEnergy()

simulation.reporters.append(DCDReporter(DCD_output_file, N_save))

simulation.reporters.append(StateDataReporter(stats_output_file, N_save, step=True, potentialEnergy=True, temperature=True))

simulation.step(100000)
```

The Openmm-Plumed kernel:
```
void ReferenceCalcPlumedForceKernel::initialize(const System& system, const PlumedForce& force) {
  plumedmain = plumed_create();
  int done_already;
  int intra_comm_rank;
  MPI_Initialized(&done_already);
  MPI_Comm intra_comm = force.getIntracom();
  MPI_Comm inter_comm = force.getIntercom();
  MPI_Comm_rank(intra_comm, &intra_comm_rank);
  if (!done_already)
  {
      MPI_Init(NULL, NULL);
  }
  if (intra_comm_rank == 0)
      plumed_cmd(plumedmain, "GREX setMPIIntercomm", &inter_comm);
  plumed_cmd(plumedmain, "GREX setMPIIntracomm", &intra_comm);
  plumed_cmd(plumedmain, "GREX init");
  hasInitialized = true;
  int apiVersion;
  plumed_cmd(plumedmain, "getApiVersion", &apiVersion);
  if (apiVersion < 4)
      throw OpenMMException("Unsupported API version.  Upgrade PLUMED to a newer version.");
  int precision = 8;
  plumed_cmd(plumedmain, "setRealPrecision", &precision);
  double conversion = 1.0;
  plumed_cmd(plumedmain, "setMDEnergyUnits", &conversion);
  plumed_cmd(plumedmain, "setMDLengthUnits", &conversion);
  plumed_cmd(plumedmain, "setMDTimeUnits", &conversion);
  plumed_cmd(plumedmain, "setMDEngine", "OpenMM");
  plumed_cmd(plumedmain, "setLog", force.getLogStream());
  int numParticles = system.getNumParticles();
  plumed_cmd(plumedmain, "setNatoms", &numParticles);
  double dt = contextImpl.getIntegrator().getStepSize();
  plumed_cmd(plumedmain, "setTimestep", &dt);
  double kT = force.getTemperature() * BOLTZ;
  if (kT >= 0.0)
      plumed_cmd(plumedmain, "setKbT", &kT);
  int restart = force.getRestart();
  plumed_cmd(plumedmain, "setRestart", &restart);
  plumed_cmd(plumedmain, "init", NULL);
}
```

**Comment by husseinmur** [comment]
Thanks for your quick answer! I placed the MPI_Init outside and it looks like the code is hanging after  `plumed_cmd(plumedmain, "GREX init");` If I remove it, the script runs and throws that same exception of float expected but received void.

And yes, the exception used to show when I was only pasing one comm (and setting it using `plumed_cmd(plumedmain, "setMPIComm", &comm);`, but it dissapeared when I wrapped the OpenMM simulation code with `if (rank == 0)` in Python. 

I tried `export PLUMED_STACK_TRACE=1` but no more info is shown. Maybe OpenMM is only returning data to one thread for some reason?

**Comment by husseinmur** [comment]
Updating the MPI comms types as you suggested solved the problem of hanging. The Plumed output shows now that it is running on multiple replicas. Thank you! 
However, the same exception is still thrown:
```
Traceback (most recent call last):
  File "/mnt/f/CALVADOS/single_chain/ACTR/mpi/simulate.py", line 146, in <module>
    simulation.minimizeEnergy()
  File "/home/hussein/miniconda3/envs/try4/lib/python3.9/site-packages/openmm/app/simulation.py", line 137, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/hussein/miniconda3/envs/try4/lib/python3.9/site-packages/openmm/openmm.py", line 17208, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException:
+++ PLUMED error
+++ message follows +++
This command expects a floating point type. Received a void instead
If you are sure your code is correct you can disable this check with export PLUMED_TYPESAFE_IGNORE=yes
In case this is necessary, please report an issue to developers of PLUMED and of the MD code
See also https://github.com/plumed/plumed2/pull/653
```
I tried to run the simulation without MPI and still, the full traceback doesn't show. Is there anything else that can be done to debug this?

**Comment by GiovanniBussi** [comment]
The raised exception says that the `plumed_cmd` has been passed an incorrect type.

You should find out which call is raising the issue, so we can see if there's really a bug in the way `plumed_cmd` was called or if there's a bug in PLUMED.

1. I made a mistake in the reply above, the correct setting is `export PLUMED_STACK_TRACE=yes`. However, this will just give you the location in the code with some approximate line numbers. It's sometime not easy to detect the exact function call.

2. If this doesn't work, you might patiently add prints to find out at which `plumed_cmd` call the code is crashing.

**Comment by GiovanniBussi** [comment]
> `plumed_cmd(plumedmain, "setVirial", &virial);`

This is an incorrect type passed (though the pointer actually has the same value, so would work if it was not for the typechecking

> `plumed_cmd(plumedmain, "setVirial", &virial[0]);`

This is the correct thing to do.

I suspect the code is now correct and there might be something wrong with the input or setup.

Can you try to use PLUMED to do something trivial, e.g. add a force equal to 1e-10 to the distance between two atoms? The system should behave as if PLUMED was not used (except for tiny numerical differences)
